// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx7pdRVr1htFjY3-wTebbRJGj8JcPRObk',
    appId: '1:78567599802:web:8076a2561402360d0c5c83',
    messagingSenderId: '78567599802',
    projectId: 'snapvel-d1375',
    authDomain: 'snapvel-d1375.firebaseapp.com',
    storageBucket: 'snapvel-d1375.firebasestorage.app',
    measurementId: 'G-9R7YP1DRSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK6C2Rw6tWXyYwwnZHvRgMxS41jkOneYw',
    appId: '1:78567599802:android:c9df4967ae7670c10c5c83',
    messagingSenderId: '78567599802',
    projectId: 'snapvel-d1375',
    storageBucket: 'snapvel-d1375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJwmihIYxP43gKUUDhnp3YzPkRtLmE_yA',
    appId: '1:78567599802:ios:a52d1488881453630c5c83',
    messagingSenderId: '78567599802',
    projectId: 'snapvel-d1375',
    storageBucket: 'snapvel-d1375.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
